### ISSUE TITLE
Unknown Wasm section warning

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#1]
Running `make ` on the example results in the following warning — although the build succeeds.

```
$ make
...
mkdir -p target
crates/spin-js-cli/target/release/spinjs -o target/spin-http-js.wasm spin-http.js
warning: unknown name subsection with id 9 at 4807649
```

**Comment by dicej** [comment]
That warning is coming from [binaryen when parsing the moodule](https://docs.rs/binaryen/0.12.1/binaryen/struct.Module.html#method.read) in order to optimize and strip it.  I'll need to dig a bit to find out what it's upset about.

**Comment by dicej** [comment]
Looks like binaryen-rs is using an out-of-date version of binaryen from before https://github.com/WebAssembly/binaryen/commit/57a9e77add02dc1d874fdbfee2c61cae8c0eefa1 was merged.  I'll try to upgrade to the latest and open a PR in the binaryen-rs repo if successful.

**Comment by dicej** [comment]
Fixed in https://github.com/fermyon/spin-http-js/commit/be7f511ade5d3356a46138c6209cd773be85b36f
