### ISSUE TITLE
Add `crypto.createHmac` and `crypto.createHash`

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#100]
These functions are extremely useful for computing signatures for payloads.

**Comment by karthik2804** [comment]
Would the `digest` method from subtleCrypto implementation on the browser work for the use cases of `createHash`? 

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest 

Or would the `update` and `digest` methods on the node API be preferred?
