### ISSUE TITLE
Spin template version compatibility tags

### ISSUE THREAD

**Issue by itowlson** [spinframework/spin-js-sdk#110]
When a user runs `spin templates install --git https://github.com/fermyon/spin-js-sdk`, Spin looks in the repo for a Git tag of the form `spin/templates/vX.Y` matching the major-minor version of Spin.

If that tag is found, Spin installs the version of the template at that tag.  This means that if a SDK makes potentially breaking changes (for example, referring to new host components), old Spin versions still install templates with compatible SDK versions.

If no tag is found, Spin 'falls forward' and installs from `main`.  This could cause Spin to pick up a template that references a SDK version that imports host services that aren't in the user's version of Spin, which would result in errors at runtime.

It would be good to start tagging the JS SDK repo with template version compatibility tags.  We probably don't need to do older versions of Spin but maybe v0.7 and v0.8 tags so that users of those versions get stable versions of the templates?

Here is an example from the Spin repo itself:

![image](https://user-images.githubusercontent.com/865538/215924804-d67386e1-fcac-4580-9086-dfed64337fe2.png)

**Comment by karthik2804** [comment]
Thanks for pointing it out @itowlson. I will look into adding tags for v0.7 and v0.8.

**Comment by karthik2804** [comment]
@itowlson Quick question regarding this. Would it be okay for the same commit to be tagged for both v0.7 and v0.8?

**Comment by itowlson** [comment]
Absolutely.  If the same version of the template is compatible with both - which in this case is very likely - then that would definitely be the way to go.

**Comment by karthik2804** [comment]
commits have been tagged for templates 

![image](https://user-images.githubusercontent.com/25023490/217645360-efc5a18c-ae21-4168-bd52-74071747ee63.png)
