### ISSUE TITLE
Publish `spinjs` as a `spin` plugin

### ISSUE THREAD

**Issue by dicej** [spinframework/spin-js-sdk#16]
~~Ideally, we'd like `spinjs` to be a published NPM package that developers can `npm add` to their project to make Spin apps.~~

~~I've never done this, myself, so I don't know the best way to do it.  A quick search turned up https://www.woubuc.be/blog/post/publishing-rust-binary-on-npm/, which might be a good place to start.~~

~~Ideally, this would be built and published via a GitHub action, but it could be just a bash script to start with.~~

Let's package `spinjs` as a `spin` plugin, and publish the TS type declarations separately as an NPM package.

**Comment by karthik2804** [comment]
We would only need to package the types  (`.d.ts`) as a package in `npm`. The source typescript part of the SDK will be bundled in the rust binary. I think that `spinjs` binary should be a part of the `spin plugins`.

**Comment by radu-matei** [comment]
The alternative to this would be using a Spin plugin.

**Comment by karthik2804** [comment]
> The alternative to this would be using a Spin plugin.

We would still need to package `types` to npm for typescript developers.

**Comment by dicej** [comment]
Yeah, I forgot about the plugin approach for `spinjs` (despite the fact that I was the one who prototyped it).  Makes sense to publish an NPM package for the types and a plugin for `spinjs`.

**Comment by karthik2804** [comment]
closed with https://github.com/fermyon/spin-plugins/pull/13
