### ISSUE TITLE
CI: Publish canary plugin builds

### ISSUE THREAD

**Issue by vdice** [spinframework/spin-js-sdk#161]
Publish canary builds of the js2wasm plugin on each merge to main, in the form of a GitHub release (should be a 'pre-release').

The plugin manifest can be co-located on the same GH release.  Ideally, the plugin manifest is auto-generated in the same CI workflow.

Users/automation can then install the canary version via `spin plugins install -u <url to the manifest>`

**Comment by karthik2804** [comment]
Canary releases are now generated on merge to main!
