### ISSUE TITLE
CI: Auto-generate plugin manifest on tag push; PR to fermyon/spin-plugins

### ISSUE THREAD

**Issue by vdice** [spinframework/spin-js-sdk#162]
When a semver tag is pushed (eg v0.5.0), auto-generate the plugin manifest filled in with all of the necessary os/arch urls and digests and then create a PR in the https://github.com/fermyon/spin-plugins repo which:

- Renames the prior latest manifest according to its version eg `js2wasm.json` becomes `js2wasm@0.4.0.json`
- Adds the auto-generated plugin manifest as the new, latest manifest, eg `js2wasm.json`

**Comment by karthik2804** [comment]
The new SDK does not rely on spin plugins anymore
