### ISSUE TITLE
Improve error messages for unimplemented functions

### ISSUE THREAD

**Issue by lann** [spinframework/spin-js-sdk#168]
https://discord.com/channels/926888690310053918/1109846409118748693

Currently it appears that unimplemented runtime functions give the somewhat confusing error: `Handler returned an error: Uncaught TypeError: not a function` (i.e. "you tried to call `undefined`")

I wonder if we could stub out at least some common APIs to give more helpful error messages.

**Comment by karthik2804** [comment]
This should be improved in v2 SDK as we now use StarlingMonkey as the engine.
