### ISSUE TITLE
Contribute a JS/TS guest binding generator to wit-bindgen and use it here

### ISSUE THREAD

**Issue by dicej** [spinframework/spin-js-sdk#18]
A proper JS/TS binding generator would eliminate the boilerplate we're currently maintaining (and must update each time we expand or change the Spin WIT files).

However, we should probably not tackle this until #17 has been addressed and wit-bindgen has stabilized.

**Comment by karthik2804** [comment]
We now use `ComponentizeJS` to generate the bindings!
