### ISSUE TITLE
Outdated quickjs-wasm-sys dependency triggering clang-16 bug

### ISSUE THREAD

**Issue by chrismatteson** [spinframework/spin-js-sdk#186]
spin-js-engine is pinned to [quickjs-wasm-sys 0.1.2](https://github.com/fermyon/spin-js-sdk/blob/main/crates/spin-js-engine/Cargo.toml#L16) while the current version is 1.1.2. quickjs-wasm-sys is pinned to bindgen 0.59.2 which has a [bug](https://github.com/rust-lang/rust-bindgen/issues/2312) with clang-16 that was fixed in this [pr](https://github.com/llvm/llvm-project/commit/19e984ef8f49bc3ccced15621989fa9703b2cd5b#diff-cde6fae42b53073a85e0901697f60ea80262705f86643b7b27524c7bd24c6f80) that was released in bindgen 0.62.

We should upgrade quickjs-wasm-sys if possible to resolve this issue.

**Comment by chrismatteson** [comment]
Specifically this is what the error that the above causes looks like when running `make` against llvm 16.0.6 on a MacBook m2:

```
  --- stderr
  thread 'main' panicked at '"enum_(unnamed_at__/quickjs/quickjs_h_67_1)" is not a valid Ident', /Users/chrismatteson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.66/src/fallback.rs:774:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [target/wasm32-wasi/release/spin-js-engine.wasm] Error 101
```

**Comment by radu-matei** [comment]
Our CI pins WASI SDK v16, which relies on LLVM14.
We should either update them to track the latest, or document the requirement.

https://github.com/fermyon/spin-js-sdk/blob/main/.github/workflows/test.yaml#L53

**Comment by redoC-A2k** [comment]
I am getting same error , even though I have installd wasi-sdk v16 and moved the content of extracted folder into /opt/wasi-sdk. Could you please help me ?

**Comment by karthik2804** [comment]
We now have a newer version of the SDK that uses `ComponentizeJS`
