### ISSUE TITLE
Add missing SDK features

### ISSUE THREAD

**Issue by dicej** [spinframework/spin-js-sdk#19]
- [x] Filesystem directory listing API (Node-style)

(TODO: add more as we think of them)

**Comment by karthik2804** [comment]
For the minimal implementation of  `fsPromise.readDir`, can we assume that filenames will always be returned as `utf-8`? Also, do we need to support the `withFileTypes` argument?

**Comment by dicej** [comment]
> For the minimal implementation of `fsPromise.readDir`, can we assume that filenames will always be returned as `utf-8`?

In general, we can't assume they'll be UTF-8, but for the time being it's reasonable to only support UTF-8 file and directory names.  If that limitation causes problems for people, we can address it later.

> Also, do we need to support the `withFileTypes` argument?

Again, I think we can live without it to start with and add it later if people (or popular libraries) need it.
