### ISSUE TITLE
Packaging and distribution for the native binary

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#2]
Building and preparing a JS component for Spin needs a CLI binary that prepares and pre-initialises runtime. This additional binary needs to be on the user's system at `spin build` time, so there needs to be a way to fetch it.

Currently, there are two ways of fetching this that I can think of:

- Spin plugin
- JS dev dependency

Any thoughts on the two, @dicej?

**Comment by dicej** [comment]
I like the Spin plugin approach since (1) it will probably be easier and (2) the user will need to have Spin installed to do anything useful with the module (e.g. `spin up` or `spin deploy` it).

**Comment by radu-matei** [comment]
I agree, a Spin plugin seems like the best approach for now.

Closing, thanks!
