### ISSUE TITLE
Why is `InferenceResult` not exported ?  

### ISSUE THREAD

**Issue by sebastienblanc** [spinframework/spin-js-sdk#218]
Looking here : https://github.com/fermyon/spin-js-sdk/blob/main/spin-sdk/src/modules/spinSdk.ts#L314 I can see that `InferenceResult`(and some others like `InferenceUsage`) are not exported . Any reasons for this ?

**Comment by itowlson** [comment]
Oddly enough they do appear in the docs (https://fermyon.github.io/spin-js-sdk/variables/Llm.html links to https://fermyon.github.io/spin-js-sdk/interfaces/_internal_.InferenceResult.html) although under an "internal" grouping.  @karthik2804 @dicej any idea what the intention is here?

**Comment by karthik2804** [comment]
I think that was just an oversight and it should be exported.

**Comment by karthik2804** [comment]
It should be exported with the new SDK.
