### ISSUE TITLE
release 0.6.1 to npm.org?

### ISSUE THREAD

**Issue by rgl** [spinframework/spin-js-sdk#219]
for some reason 0.6.1 is not available at https://www.npmjs.com/package/@fermyon/spin-sdk. the latest available version 0.6.0.

**Comment by karthik2804** [comment]
The patch versions between the plugin binary and the SDK package on npm do not always match. As long as the minor versions match, they should be compatible. 

Due to compatibility issues, the patch version for the binary was bumped to build the plugin using Ubuntu 20.04 instead of 22.04.

**Comment by rgl** [comment]
Ah, so there's no problem with the release pipeline. Got it. Thanks!
