### ISSUE TITLE
Add methods to the request object

### ISSUE THREAD

**Issue by karthik2804** [spinframework/spin-js-sdk#24]
It would be nice if we could add the following methods to the HttpRequest interface to allow for easier handling of requests.
- [x] `json`
- [x] `text`
- [ ] `formdata`

**Comment by karthik2804** [comment]
Formdata can be handled using the npm library https://www.npmjs.com/package/parse-multipart-data

**Comment by radu-matei** [comment]
Is there a documented way to do that?
