### ISSUE TITLE
[feat/sdk-v2]: test application does not use local SDK

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#245]
The test script that is run on PRs on the `feat/sdk-v2` branch is using the published version of the SDK, meaning we don't actually test changes to the SDK on GH Action runs.

We should update the SDK dependency to point to the local SDK.

**Comment by radu-matei** [comment]
Because of the above, the test app is currently not building with the latest version of the SDK.

**Comment by karthik2804** [comment]
Updated in 
https://github.com/fermyon/spin-js-sdk/pull/244/commits/86eff5bac64da7b6d96c7f9d0f01003a9d4f7d7c

**Comment by karthik2804** [comment]
This has now been fixed.
