### ISSUE TITLE
please drop/rename the v2.10 tag

### ISSUE THREAD

**Issue by rgl** [spinframework/spin-js-sdk#299]
the https://github.com/fermyon/spin-js-sdk/releases/tag/v2.10 was wrongly created and it should have been v2.1.0. can you please fix that?

this breaks tools like renovate which are looking for the latest version by interpreting the tag as a version number. as such, renovate thinks the latest version of this repository is 2.10 instead of 2.3.

**Comment by karthik2804** [comment]
@rgl Thank you for the catch. I have fixed the typo in the tag.
