### ISSUE TITLE
Re-enable optimization on Windows

### ISSUE THREAD

**Issue by dicej** [spinframework/spin-js-sdk#58]
In https://github.com/fermyon/spin-js-sdk/commit/be913b9e99aa5d08e2946b8899a3bc67f5164f74, we had to disable `binaryen` optimization for the Windows build because it was generating corrupt Wasm files.  We should try with the latest release of `binaryen` to see if it's still an issue.  If not, then lets upgrade.  If so, then let's report the issue upstream.

Also, https://github.com/brson/wasm-opt-rs seems to be getting more attention than https://github.com/pepyakin/binaryen-rs, so we might want to switch.

**Comment by karthik2804** [comment]
We now have a newer version of the SDK that uses `ComponentizeJS`
