### ISSUE TITLE
Rename NPM package to `@fermyon/spin-sdk`

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#59]
This way, when importing, it would go from

```
import { HandleRequest, HttpResponse} from "@fermyon/spin-sdk-types"
```

to

```
import { HandleRequest, HttpResponse} from "@fermyon/spin-sdk"
```

Additionally, we might want to extend the SDK to include other things, not just types.

**Comment by karthik2804** [comment]
This package is meant only to add TypeScript support as any implementation added will be a part of the binary published as Spin `plugin`.

**Comment by radu-matei** [comment]
Right — but this is _the_ public package someone brings in when they want to create a Spin application — and there is a discrepancy between all other SDKs (which are `spin-sdk` or `spin_sdk`) and this one.

**Comment by karthik2804** [comment]
That makes sense. Should I go ahead and change the name of the package? @radu-matei

**Comment by karthik2804** [comment]
The package has been renamed. I will make a follow-up PR to adjust the templates and the examples.
