### ISSUE TITLE
Linux ARM64 Support

### ISSUE THREAD

**Issue by bhummerstone** [spinframework/spin-js-sdk#77]
Hi folks! Loving spin so far, but I'm doing my development on a Linux ARM64 machine: is it possible to support this architecture in coming releases, please?

**Comment by radu-matei** [comment]
Hey, thanks for reaching out!

We now have Linux ARM64 support for Spin itself (see https://github.com/fermyon/spin/releases), and it makes a lot of sense to have it for the JS plugin as well.

@karthik2804 already started this in #78, and we hope to merge this soon.

Thanks!
