### ISSUE TITLE
Spin build fails when using the one of the templates from spin-js-sdk

### ISSUE THREAD

**Issue by bindea-mihai** [spinframework/spin-js-sdk#83]
## Steps to reproduce
- use the steps from [here](https://developer.fermyon.com/spin/javascript-components) to init and build a new ts component
i.e. 
```
> spin new http-ts ts-hello-test --accept-defaults
> npm install
> spin build
```
- run `spin build` again

Result: When running `spin build` for the 2nd time you get the following error
![image](https://user-images.githubusercontent.com/10978867/209134796-8a2061b2-654a-41e7-b745-4393efd121cd.png)

## Workaround
In order to build your app for the 2nd time, you need to manually delete the following folders: `-p`, `dist` and `target`

## Other info:
OS: `Windows 11 Pro, Version	10.0.22621 Build 22621`
Spin: `0.7.1 (6cf7447 2022-12-19)`
Spin plugin: `js2wasm 0.1.0`

**Comment by karthik2804** [comment]
Thanks for identifying this issue. This issue seems to be isolated to windows due to the lack of a `-p` argument on `mkdir`. I will look into it.

**Comment by karthik2804** [comment]
It looks like `npm` by default uses `cmd.exe`. One solution would be to configure `npm` to use git bash using the following command. 

```bash
npm config set script-shell "C:\\Program Files (x86)\\git\\bin\\bash.exe"  
```

Let me know if that fixes it.

**Comment by bindea-mihai** [comment]
Worked like a charm. 
One mention though, git is installed in `C:\\Program Files\\git\\bin\\bash.exe`

**Comment by bindea-mihai** [comment]
That also explains why the `-p` folder was created

**Comment by itowlson** [comment]
@karthik2804 Is the `-p` really needed there?  It seems to be creating only one level of directory.

**Comment by karthik2804** [comment]
@itowlson On Unix systems it let's the command run without failing if the directory already exists. 

```
-p, --parents no error if existing, make parent directories as needed, with their file modes unaffected by any -m option
```

**Comment by itowlson** [comment]
TIL!  Thanks Karthik!

**Comment by karthik2804** [comment]
Can we close this issue @bindea-mihai

**Comment by tpmccallum** [comment]
Docs have also been updated Re: this issue.
https://github.com/fermyon/developer/pull/299
Thanks @bindea-mihai for raising this also.
